[package]
name = "usb_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
usb_enumeration = "0.2.0"
serialport = "4.2.2"
uuid = "1.4.1"
printers = "1.2.0"
